Fix issue #11 - Report user photos
billsonnn/nitro-react pull request #78
Opened 2022-12-08 15:12 UTC by oobjectt

2022-12-09 00:14 UTC, dank074 requested changes

2022-12-09 00:14 UTC, dank074 commented on src/components/help/views/ReportSummaryView.tsx
> -            case ReportType.PHOTO:
Why remove this? This is how flash works and I think we should stick to original functionality

2022-12-09 00:14 UTC, dank074 commented on src/components/help/views/ReportSummaryView.tsx
> +            case ReportType.PHOTO: {
No need to add it here, since photo reports should be handled using a separate packet, if we want to stick to flash functionality

2022-12-09 00:14 UTC, dank074 commented on src/hooks/help/useHelp.ts
> -            case ReportType.PHOTO:
For a photo report we should need: activeReport.extraData (which is the photo url for photo furnitures), activeReport.cfhTopic, roomId, and the reported photo furniture id

2022-12-11 20:26 UTC, oobjectt commented
Changed made.

Sorry if I don't make the changes correctly, I'm learning how to use requests with the emulator, and I'm also a beginner in React.

Anything, I'm willing to help and get the changes right.

Thank you !

2022-12-12 06:34 UTC, dank074 commented
> Changed made.
> 
> Sorry if I don't make the changes correctly, I'm learning how to use requests with the emulator, and I'm also a beginner in React.
> 
> Anything, I'm willing to help and get the changes right.
> 
> Thank you !

yeah no worries, your react code looks fine, only changes that were needed was so that it matched flash functionality. I will review this again

2022-12-12 06:48 UTC, dank074 approved these changes
Good job it looks good to me 👍 pinging @billsonnn for a review

2022-12-14 04:44 UTC, merged