Issue #75 - Room settings tags
billsonnn/nitro-react pull request #87
Opened 2022-12-13 00:50 UTC by oobjectt

Tags has come to Nitro!
Added the 'YoVoy' field in the room settings.

![imagen](https://user-images.githubusercontent.com/110488133/207198495-1baf198d-6736-4543-b59e-3c53c8ccc988.png)

If the user types an inappropriate word or restricted words, the user will send a message that the tag cannot be put on.

![imagen](https://user-images.githubusercontent.com/110488133/207198705-87a168b9-14cf-4d6d-a363-02242c2c91f3.png)

When you click on the tag information, it will automatically redirect to the browser and look for the 'YoVoy' filter

![imagen](https://user-images.githubusercontent.com/110488133/207198962-68d47595-a88a-49d4-af22-9e839d9bf698.png)

2022-12-13 01:40 UTC, dank074 requested changes

2022-12-13 01:40 UTC, dank074 commented on src/api/navigator/RoomSettingsErrorType.ts
> +export class RoomSettingsErrorType
You don't need to create these enums, they are already defined in `RoomSettingsSaveErrorParser` in the renderer

2022-12-13 01:40 UTC, dank074 commented on src/components/navigator/views/room-settings/NavigatorRoomSettingsBasicTabView.tsx
> +            case RoomSettingsErrorType.RESTRICTED_TAGS:
use the values provided in `RoomSettingsSaveErrorParser` (for example `RoomSettingsSaveErrorParser.ERROR_INVALID_TAG`. Also make sure you use the correct localization for each error type (you can check the localization for each error type here: https://github.com/dank074/HabboSwfOpenSource/blob/5bad64a6704e38576c96c08a7a3a246305e31a92/src/com/sulake/habbo/navigator/roomsettings/RoomSettingsCtrl.as#L336)

2022-12-13 20:55 UTC, oobjectt commented
Made !

Thank you very much for your advice, also thanks for the page, I was unaware of it.

Thanks for all the feedback! 👍

2022-12-14 00:24 UTC, dank074 approved these changes
looks good

2022-12-14 04:45 UTC, merged